Project 1/Project1/models.py
from pytz import timezone
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Note(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    data = db.Column(db.String(400))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String(150), unique = True)
    password = db.Column(db.String(150))
    username = db.Column(db.String(150))
    notes = db.relationship('Note')

Project 1/Project1/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import os
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME  = "databadse.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY']  = "hakdhkagladkfgadkkadgfladsjgkfd3242526@#$%@adfad"
    app.config['SQLALCHEMY_DATABASE_URI']= f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .models import Note, User

    create_database(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix = '/')
    app.register_blueprint(auth, url_prefix = '/')

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)
    
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    
    return app


def create_database(app):
    if not(os.path.exists('project1/' +DB_NAME)):
        db.create_all(app = app)
        print('Created Database')

 

Project 1/Project1/auth.py
from unicodedata import category
from flask import Blueprint, render_template, request, flash, redirect,url_for
import re
from .models import User, Note
from werkzeug.security import generate_password_hash, check_password_hash
from . import db 
from flask_login import login_required, logout_user, login_user, current_user


regex = re.compile(r'([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\.[A-Z|a-z]{2,})+')
      

auth = Blueprint('auth', __name__)

@auth.get('/login')
@auth.post('/login')
def login():
    if request.method =='POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username = username).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully', category = 'success')
                login_user(user, remember = True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password. please enter correct password', catogory = 'error')

        else:
            flash("The username doesnot exits. Please enter correct credentials",category = "error")

    return render_template("login.html", user = current_user)
    


@auth.get('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.get('/signup')
@auth.post('/signup')
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        username = request.form.get('username')

        user = User.query.filter_by(email = email).first()

        if user:
            flash("The user already exists.", category = 'error')

        elif (re.fullmatch(regex, email)) and (password1 == password2) and len(username)>4:
            new_user = User(email = email, username = username, password = generate_password_hash(password1, method = "sha256"))
            db.session.add(new_user)
            db.session.commit()
            flash("The account is created", category = "success")
            return redirect(url_for('auth.login'))
        else:
            flash("The credentials you entered is not valid", category = 'error')

    return  render_template("signup.html",user= current_user)

Project 1/Project1/views.py
from flask import Blueprint, render_template, request, flash
from flask_login import login_required, current_user
from .models import Note
from . import db
import json, jsonify



views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    return render_template("home.html", user = current_user)

@views.route('/products')
@login_required
def products():
    return render_template("products.html", user = current_user)

@views.post('/notes')
@views.get('/notes')
@login_required
def notes():
    if request.method == 'POST':
        note = request.form.get('note')
    
        if len(note) < 1:
            flash("The note cannot be empty", category = "error")
        else:
            new_note = Note(data = note, user_id = current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash("New Note added", category = "success")
    
    return render_template("notes.html", user = current_user)

@views.post('/delete-note')
@login_required
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
            
    return jsonify({})

Project 1/Project1/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %} {% endblock title %}</title>
  <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet" />
  <script type = "text/javascript" src= "{{ url_for('static', filename='js/index.js') }}"></script>
</head>

<body>
  <!-- ====== Navbar Section Start -->
  <header x-data="
            {
              navbarOpen: false
            }
          " class="bg-white w-full flex items-center">
    <div class="container">
      <div class="flex -mx-4 items-center justify-between relative">
        <div class="px-4 w-60 max-w-full">
          <a href="javascript:void(0)" class="w-full block py-5">
            <img src="https://cdn.tailgrids.com/1.0/assets/images/logo/logo.svg" alt="logo" class="w-full" />
          </a>
        </div>
        <div class="flex px-4 justify-between items-center w-full">
          
          <div>
            <button @click="navbarOpen = !navbarOpen" :class="navbarOpen && 'navbarTogglerActive' " id="navbarToggler"
              class="block absolute right-4 top-1/2 -translate-y-1/2 lg:hidden focus:ring-2 ring-primary px-3 py-[6px] rounded-lg">
              <span class="relative w-[30px] h-[2px] my-[6px] block bg-body-color"></span>
              <span class="relative w-[30px] h-[2px] my-[6px] block bg-body-color"></span>
              <span class="relative w-[30px] h-[2px] my-[6px] block bg-body-color"></span>
            </button>
            <nav :class="!navbarOpen && 'hidden' " id="navbarCollapse"
              class="absolute py-5 px-6 bg-white shadow rounded-lg max-w-[250px] w-full lg:max-w-full lg:w-full right-4 top-full lg:block lg:static lg:shadow-none">
             {% if user.is_authenticated %}
              <ul class="blcok lg:flex">
                <li>
                  <a href="/"
                    class="text-base font-medium text-dark hover:text-primary py-2 lg:inline-flex flex lg:ml-12">
                    Home
                  </a>
                </li>
                <li>
                  <a href="{{ url_for('views.notes') }}"
                    class="text-base font-medium text-dark hover:text-primary py-2 lg:inline-flex flex lg:ml-12">
                    Notes
                  </a>
                </li>
                <li>
                  <a href="{{ url_for('views.products') }}"
                    class="text-base font-medium text-dark hover:text-primary py-2 lg:inline-flex flex lg:ml-12">
                    Products
                  </a>
                </li>
              </ul>
              {% endif %}
            </nav>
          </div>

          <div class="sm:flex justify-end hidden pr-16 lg:pr-0">
            {% if user.is_authenticated %}
           
            <a href="{{url_for('auth.logout')}}" class="text-base font-medium text-dark hover:text-primary py-3 px-7">
              Logout
            </a>
            {% else%}

            <a href="/login" class="text-base font-medium text-dark hover:text-primary py-3 px-7">
              Login
            </a>
            <a href="/signup"
              class="text-base font-medium text-black bg-primary rounded-lg py-3 px-7 hover:bg-opacity-90 ml-3">Sign Up
            </a>

            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- ====== Navbar Section End -->

  {% with messages = get_flashed_messages(with_categories =true) %} {% if
  messages %} {% for category,message in messages %} {% if category == 'error'
  %}
  <div id="alert-2" class="flex p-4 mb-4 bg-red-100 rounded-lg dark:bg-red-200" role="alert">
    <svg class="flex-shrink-0 w-5 h-5 text-red-700 dark:text-red-800" fill="currentColor" viewBox="0 0 20 20"
      xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd"
        d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
        clip-rule="evenodd"></path>
    </svg>
    <div class="ml-3 text-sm font-medium text-red-700 dark:text-red-800">
      {{message}}
    </div>
    <button type="button"
      class="ml-auto -mx-1.5 -my-1.5 bg-red-100 text-red-500 rounded-lg focus:ring-2 focus:ring-red-400 p-1.5 hover:bg-red-200 inline-flex h-8 w-8 dark:bg-red-200 dark:text-red-600 dark:hover:bg-red-300"
      data-collapse-toggle="alert-2" aria-label="Close">
      <span class="sr-only">Close</span>
      <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
          d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
          clip-rule="evenodd"></path>
      </svg>
    </button>
  </div>
  {% else %}
  <div id="alert-3" class="flex p-4 mb-4 bg-green-100 rounded-lg dark:bg-green-200" role="alert">
    <svg class="flex-shrink-0 w-5 h-5 text-green-700 dark:text-green-800" fill="currentColor" viewBox="0 0 20 20"
      xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd"
        d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
        clip-rule="evenodd"></path>
    </svg>
    <div class="ml-3 text-sm font-medium text-green-700 dark:text-green-800">
      {{message}}
    </div>
    <button type="button"
      class="ml-auto -mx-1.5 -my-1.5 bg-green-100 text-green-500 rounded-lg focus:ring-2 focus:ring-green-400 p-1.5 hover:bg-green-200 inline-flex h-8 w-8 dark:bg-green-200 dark:text-green-600 dark:hover:bg-green-300"
      data-collapse-toggle="alert-3" aria-label="Close">
      <span class="sr-only">Close</span>
      <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
          d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
          clip-rule="evenodd"></path>
      </svg>
    </button>
  </div>
  {% endif %} {% endfor %} {% endif %} {% endwith %} {% block content%} {%
  endblock content %}
</body>

</html>

Project 1/Project1/templates/home.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock title %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
      <div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Welcome to the tutorial of
          <br class="hidden lg:inline-block">web development with Flask
        </h1>
        <p class="mb-8 leading-relaxed text-justify">Flask is a micro web framework written in Python. It is classified as a microframework because it does not require particular tools or libraries. It has no database abstraction layer, form validation, or any other components where pre-existing third-party libraries provide common functions. However, Flask supports extensions that can add application features as if they were implemented in Flask itself. Extensions exist for object-relational mappers, form validation, upload handling, various open authentication technologies and several common framework related tools.</p>
        <div class="flex justify-center">
          <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"><a href = "https://en.wikipedia.org/wiki/Flask_(web_framework)" target="_blank">About Flask </a></button>
          <button class="ml-4 inline-flex text-gray-700 bg-yellow-500 border-0 py-2 px-6 focus:outline-none hover:bg-yellow-600 rounded text-lg"> <a href ="{{ url_for('views.notes') }}"  target = "_blank">View and Create notes</a></button>
        </div>
      </div>
      <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
        <img class="object-cover object-center rounded" alt="hero" src="{{ url_for('static', filename='images/landing_page.jpg') }}">
      </div>
    </div>
  </section>

{% endblock content %}

Project 1/Project1/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock title %}

{% block content %}
   
<!-- component -->
<div class="container signup">
    <div class="min-h-screen flex mb-4 row-signup">
            <div class="w-3/5 h-12 row-right">
              
                <div class="text-dig">
                    <p class="w-full text-base sm:text-lg md:text-xl text-center lg:text-2xl xl:text-5xl">
                            Sign here<br> to start working <br> on some amazing projects
                    </p>
                  <div class="text-center mb-4 w-3/5">
                    <img src="https://cdn.dribbble.com/users/79571/screenshots/5516891/workflow_4x.png">
                  </div>
                </div>
            </div>
            <div class="w-2/5  h-12 row-left">
                <div class="text-singup mb-8">
                
                </div>
                <div class="form-signup-dig">
                        <div class="w-full max-w-xs">
                                <form class="max-w-md mb-4 form-input" method = "POST">
                                  <div class="mb-4">
                                    <label class="block text-grey-darker text-sm font-bold mb-2" for="username">
                                      Username
                                    </label>
                                    <input class="shadow appearance-none border rounded w-full h-12 py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" name = "username" id="username" type="text" placeholder="Username">
                                  </div>
                                  <div class="mb-6">
                                        <label class="block text-grey-darker text-sm font-bold mb-2" for="password">
                                          Password
                                        </label>
                                        <input class="shadow appearance-none border border rounded w-full h-12 py-2 px-3 text-grey-darker mb-3 leading-tight focus:outline-none focus:shadow-outline" name = "password" id="password" type="password" placeholder="******************">
                                      </div>
                                  <div class="flex items-center justify-between">
                                    <button class="bg-blue hover:bg-blue-dark text-blue-700 font-bold w-full h-12 py-2 px-4  rounded focus:outline-none focus:shadow-outline" type="submit">
                                      Sign In
                                    </button>
                                  </div>
                            </form>
                               
                  </div>
                </div>
            </div>
    </div>              
                 
</div>


{% endblock content %}

Project 1/Project1/templates/notes.html
{% extends 'base.html' %}

{% block title %}
Notes
{% endblock title %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex items-center lg:w-3/5 mx-auto sm:flex-row flex-col">
            {% for note in user.notes %}
            <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0 mb-1">
                <p class="leading-relaxed text-base">{{note.data}}
                </p>
                <button class ="p-2" type = "button" onclick='DeleteNote({{note.id}})'>
                    <span class = "text-slate-800" aria-hidden="true">&#215;</span>
                </button>
            </div>
            {% endfor %}
        </div>
        <br />
        <hr />
        <form class="form flex justify-center mt-3" method  = "POST">
            <div class="flex items-center border-b border-teal-500 py-2">
              <input class="appearance-none bg-transparent border-none w-full text-slate-700 mr-3 py-1 px-2 leading-tight focus:outline-none" type="text" name = "note" id = "note" placeholder="Enter your notes">
              <button class="flex-shrink-0 border-transparent border-4 text-teal-500 hover:text-teal-800 text-sm py-1 px-2 rounded" type="submit">
                Add note
              </button>
            </div>
        </form>
    </div>
</section>


{% endblock content %}

Project 1/Project1/templates/products.html
{% extends 'base.html' %}

{% block title %}
    Products
{% endblock title %}
 
{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
      <div class="lg:w-2/3 mx-auto">
        <div class="flex flex-wrap w-full bg-gray-100 py-32 px-10 relative mb-4">
          <img alt="gallery" class="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src = "{{ url_for('static', filename='images/product1.jpg') }}" />
          <div class="text-center relative z-10 w-full">
            <h2 class="text-2xl text-gray-900 font-medium title-font mb-2">Product no 1</h2>
            <p class="leading-relaxed">This is one of the best product that we have in our store</p>
            <a class="mt-3 text-indigo-500 inline-flex items-center">Learn More
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
        <div class="flex flex-wrap -mx-2">
          <div class="px-2 w-1/2">
            <div class="flex flex-wrap w-full bg-gray-100 sm:py-24 py-16 sm:px-10 px-6 relative">
              <img alt="gallery" class="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="{{ url_for('static', filename='images/product2.jpg') }}">
              <div class="text-center relative z-10 w-full">
                <h2 class="text-xl text-gray-900 font-medium title-font mb-2">Product no 2</h2>
                <p class="leading-relaxed">This is another product that we have in our store which is also very good.</p>
                <a class="mt-3 text-indigo-500 inline-flex items-center">Learn More
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                  </svg>
                </a>
              </div>
            </div>
          </div>
          <div class="px-2 w-1/2">
            <div class="flex flex-wrap w-full bg-gray-100 sm:py-24 py-16 sm:px-10 px-6 relative">
              <img alt="gallery" class="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="{{ url_for('static', filename='images/product3.jpg') }}">
              <div class="text-center relative z-10 w-full">
                <h2 class="text-xl text-gray-900 font-medium title-font mb-2">Product no 3</h2>
                <p class="leading-relaxed">This is the most expensive product that we have in our store/shop</p>
                <a class="mt-3 text-indigo-500 inline-flex items-center">Learn More
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                  </svg>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>    

{% endblock content %}

Project 1/Project1/templates/signup.html
{% extends 'base.html' %}
{% block title %}
    Signup
{% endblock title %}
{% block content %}
<!-- component -->
<div class="container signup">
    <div class="min-h-screen flex mb-4 row-signup">
            <div class="w-3/5 h-12 row-right">
              
                <div class="text-dig">
                    <p class="w-full text-base sm:text-lg md:text-xl text-center lg:text-2xl xl:text-5xl">
                            Join the millions <br> be a flask developer <br> to meet with CoqDig
                    </p>
                  <div class="text-center mb-4 w-3/5">
                    <img src="https://cdn.dribbble.com/users/79571/screenshots/5516891/workflow_4x.png">
                  </div>
                </div>
            </div>
            <div class="w-2/5  h-12 row-left">
                <div class="text-singup mb-8">
                    <h2 class="">
                        Join us for free
                    </h2>
                </div>
                <div class="form-signup-dig">
                        <div class="w-full max-w-xs">
                                <form class="max-w-md mb-4 form-input" method="post">
                                  <div class="mb-4">
                                    <label class="block text-grey-darker text-sm font-bold mb-2" for="username">
                                      Username
                                    </label>
                                    <input class="shadow appearance-none border rounded w-full h-12 py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" id="username" name = "username" type="text" placeholder="Username">
                                  </div>
                                  <div class="mb-4">
                                    <label class="block text-grey-darker text-sm font-bold mb-2" for="email">
                                      Email
                                    </label>
                                    <input class="shadow appearance-none border border rounded h-12 w-full py-2 px-3 text-grey-darker mb-3 leading-tight focus:outline-none focus:shadow-outline" id="email" name = "email" type="email" placeholder="email">
                                  </div>
                                  <div class="mb-6">
                                        <label class="block text-grey-darker text-sm font-bold mb-2" for="password1">
                                          Password
                                        </label>
                                        <input class="shadow appearance-none border border rounded w-full h-12 py-2 px-3 text-grey-darker mb-3 leading-tight focus:outline-none focus:shadow-outline" id="password1" name = "password1" type="password" placeholder="******************">
                                      </div>
                                    <div class="mb-6">
                                        <label class="block text-grey-darker text-sm font-bold mb-2" for="password2">
                                          Re-enter Password
                                        </label>
                                        <input class="shadow appearance-none border border rounded w-full h-12 py-2 px-3 text-grey-darker mb-3 leading-tight focus:outline-none focus:shadow-outline" id="password2" name = "password2" type="password" placeholder="******************">
                                      </div>
                                  <div class="flex items-center justify-between">
                                    <button class="bg-blue hover:bg-blue-dark text-blue-600 font-bold w-full h-12 py-2 px-4  rounded focus:outline-none focus:shadow-outline" type="submit">
                                      Sign Up
                                    </button>
                                  </div>
                                </form>
                               
                  </div>
                </div>
            </div>
    </div>              
                 
</div>

{% endblock content %}